### ISSUE TITLE
Missing icons for ViUR default protoypes

### ISSUE THREAD

**Issue by phorward** [viur-framework/icons#2]
Hi there,

in the `feature/viur-3.0` branch, I'm missing the icons for **singleton** (https://github.com/viur-framework/icons/blob/master/modules/singleton.svg) and **tree** (https://github.com/viur-framework/icons/blob/master/modules/tree.svg).

These are ViUR  default prototypes, and desribe the generic functionality *singleton* => the exists only one database entry for the module, and **tree**, which is like a hierarchy, but with determination between nodes and leafs.

Will the be replacements in the new icon set?

**Comment by phneutral** [comment]
The icons »hierarchy« or »filesystem« can be used to represent tree modules. 
i really liked the old singleton icon. But a generic singleton module could just as well use »flag« or »list-item« .

In the end one would want to change the icon anyway according to the purpose of the module.
